############################################################
##    FILENAME:   preprocess.py    
##    VERSION:    1.0
##    SINCE:      2014-11-14
##    AUTHOR: 
##        Jimmy Lin <jimmylin@cs.utexas.edu>*
##        Hsiang-Fu Yu <rofuyu@cs.utexas.edu>
##        Zhong Kai <zhongkai@ices.utexas.edu>
##        Ian Yen <ianyen@cs.utexas.edu>   
##
############################################################
##    Edited by MacVim
##    Documentation auto-generated by Snippet 
############################################################

import sys
import csv
FEAT_SEP = ","
INS_SEP = "\n"

############################################################
## output file
libSVMFile = sys.argv[1]
############################################################


f = open ("./datasets/final_samp_sep2013_mask_A.txt1", "r")
#f = open ("./datasets/test_data.csv", "r")
outfile = open(libSVMFile, "w")

row = f.readline()
headers = row.split(FEAT_SEP)
del headers[1]
del headers[1]
numFeatures = len(headers)
print(numFeatures)
outfile.write(headers[0])
for j in range(1, numFeatures):
    outfile.write("," + headers[j])
while row:
    row = f.readline()
    row.strip()
    if not row: 
        continue
    ins = row.split(",")
    del ins[1]
    del ins[1]
    outfile.write(ins[0])
    for j in range(1, numFeatures):
        outfile.write("," + ins[j])
outfile.close()
